networks:
  default:
    name: rep-log-network
    external: true

services:
  master:
    image: distributed-systems-master:latest
    container_name: master
    build:
      context: .
      target: run-master
    ports:
      - "8085:8085"
    environment:
      HTTP_SERVER_PORT: 8085
      SECONDARY_ADDRESSES: "secondary1:9008;secondary2:9009"

  secondary1:
    image: distributed-systems-secondary:latest
    container_name: secondary1
    build:
      context: .
      target: run-secondary
    ports:
      - "8086:8086"
      - "9008:9008"
    environment:
      HTTP_SERVER_PORT: 8086
      GRPC_SERVER_PORT: 9008

  secondary2:
    image: distributed-systems-secondary:latest
    container_name: secondary2
    build:
      context: .
      target: run-secondary
    ports:
      - "8087:8087"
      - "9009:9009"
    environment:
      HTTP_SERVER_PORT: 8087
      GRPC_SERVER_PORT: 9009


